### ISSUE TITLE
trying to build and get a error 

### ISSUE THREAD

**Issue by docfactory37** [digrouz/docker-lidarr#1]
Hi im trying to build this docker images and i get this error when trying to build hoping you would be able to help 

![image](https://user-images.githubusercontent.com/20963053/84235843-e3b50b80-ab39-11ea-837a-ded9df21dabc.png)

**Comment by digrouz** [comment]
Hello,

Did you modify the Dockerfile ?

As I understand, you are installing chromaprint without having the testing repo enabled. As this package is from the testing repo, you should install it from there like it's done in my Dockerfile using the switch **--repository http://nl.alpinelinux.org/alpine/edge/testing** 
`apk add --no-cache --repository http://nl.alpinelinux.org/alpine/edge/testing  chromaprint`

I hope this help.

**Comment by docfactory37** [comment]
no i have not change any of the dockerfile just trying to run a standard build i have just downloads the master branch and ran it

docker build -t docfactory/lidarr:latest .

**Comment by digrouz** [comment]
please revert any change in your local copy of the repo and try again like this:

    cd /path/to/repo
    git reset --hard
    git pull
    docker build --tag docfactory37/lidarr:latest -f Dockerfile_alpine .

If you look closely to the last version of my Dockerfile_alpine, you should see the RUN start with a "set -x" which should display a lot more of information during build time. If you don't get them, it means you are not building my last working version

**Comment by docfactory37** [comment]
> please revert any change in your local copy of the repo and try again like this:
> 
> ```
> cd /path/to/repo
> git reset --hard
> git pull
> docker build --tag docfactory37/lidarr:latest -f Dockerfile_alpine .
> ```
> 
> If you look closely to the last version of my Dockerfile_alpine, you should see the RUN start with a "set -x" which should display a lot more of information during build time. If you don't get them, it means you are not building my last working version

But i only copyed it tonight / today?

**Comment by docfactory37** [comment]
i have just redownload it now and tryed a build and i got the below:

![image](https://user-images.githubusercontent.com/20963053/84254579-c0e42080-ab54-11ea-9eaa-6d8931c2eeb7.png)

**Comment by digrouz** [comment]
Ho i see now, thanks.

I'm at work so i'll fix it this evening, mostlikeky linked to the fact that since Alpine 3.12 is out, chromaprint from edge/testing is build on top of alpine 3.12 instead of 3.11. 

If you want to try up yourself before tonight, just update the first line of Dockerfile_alpine:

From:

    FROM alpine:3.11

To:

    FROM alpine:3.12

**Comment by docfactory37** [comment]
awesome thank you for the quick response i will try this and let you how i go :)

**Comment by docfactory37** [comment]
i have tested the build with the updated alpine version 3.12 and it has fixed the build issue.

thank for your quick response :)
